name: build

on:
  push:
    branches:
      - "master"
      - "develop"
    tags:
      - 'v*'
  pull_request:

permissions:
  contents: write
  packages: write

jobs:
  web:
    name: Build web
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.2.0

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: 'web/pnpm-lock.yaml'

      - name: Install dependencies
        run: cd web && pnpm install

      - name: Build
        run: cd web && pnpm run build

      - name: Upload web build
        uses: actions/upload-artifact@v3
        with:
          name: web-dist
          path: web/dist

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: web
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download web production build
        uses: actions/download-artifact@v3
        with:
          name: web-dist
          path: web/dist

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          cache: true

      - name: Test
        run: go test -v ./...

  goreleaserbuild:
    name: Build Go binaries
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: [ web, test ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download web production build
        uses: actions/download-artifact@v3
        with:
          name: web-dist
          path: web/dist

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          cache: true

      - name: Run GoReleaser build
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --skip-publish --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload assets
        uses: actions/upload-artifact@v3
        with:
          name: syncyomi
          path: dist/*

  goreleaserpublish:
    name: Build & Publish
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [ web, test ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download web production build
        uses: actions/download-artifact@v3
        with:
          name: web-dist
          path: web/dist

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          cache: true

      - name: Run GoReleaser build and publish tags
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload assets
        uses: actions/upload-artifact@v3
        with:
          name: syncyomi
          path: dist/*

  docker:
    name: Build & Publish Docker images
    runs-on: ubuntu-latest
    needs: [ web, test ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download web production build
        uses: actions/download-artifact@v3
        with:
          name: web-dist
          path: web/dist

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/syncyomi/syncyomi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and publish image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./ci.Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          push: ${{ github.repository_owner == 'SyncYomi' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILDTIME=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
            VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
            REVISION=${{ github.event.pull_request.head.sha }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}